import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Head from "next/head";
import React from "react";
import styles from "@/styles/Home.module.css";
import { Box, Text } from "@chakra-ui/react";
import Slider from "react-slick";
import NewsCard from "@/components/newsCard";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import { getNews } from "@/redux/news/news.actions";
import { State } from "../redux/store";
import { AiOutlineMobile, AiOutlineTablet } from "react-icons/ai";
import {
  BsLaptop,
  BsSmartwatch,
  BsSpeaker,
  BsHeadphones,
  BsCamera,
} from "react-icons/bs";
import { IoTvOutline } from "react-icons/io5";
import { GiConsoleController, GiWashingMachine } from "react-icons/gi";
import { CgSmartHomeRefrigerator, CgGames } from "react-icons/cg";
import { getMobile } from "@/redux/products/products.actions";

// function SampleNextArrow(props: any) {
//   const { className, style, onClick } = props;
//   return (
//     <div
//       className={className}
//       style={{ ...style, display: "block", background: "black", color: "black" }}
//       onClick={onClick}
//     />
//   );
// }

// function SamplePrevArrow() {
//   // const { className, style, onClick } = props;
//   return (
//     <div
//       // className={className}
//       style={{ display: "block", background: "green" }}
//       // onClick={onClick}

//     </div>
//   );
// }

export default function Home() {
  const productFinderArr = [
    {
      name: "Mobiles",
      icon: AiOutlineMobile,
    },
    {
      name: "Laptops",
      icon: BsLaptop,
    },
    {
      name: "TV",
      icon: IoTvOutline,
    },
    {
      name: "Tablets",
      icon: AiOutlineTablet,
    },
    {
      name: "Smart Watches",
      icon: BsSmartwatch,
    },
    {
      name: "Headphones",
      icon: BsHeadphones,
    },
    {
      name: "Cameras",
      icon: BsCamera,
    },
    {
      name: "Gaming Consoles",
      icon: GiConsoleController,
    },
    {
      name: "Speakers",
      icon: BsSpeaker,
    },
    {
      name: "Refrigerator",
      icon: CgSmartHomeRefrigerator,
    },
    {
      name: "Washing Machine",
      icon: GiWashingMachine,
    },
    {
      name: "Games",
      icon: CgGames,
    },
  ];
  const settings = {
    speed: 200,
    infinite: false,
    slidesToShow: 8,
    slidesToScroll: 3,
  };
  const ComparisonCarouselSettings = {
    speed: 200,
    infinite: false,
    slidesToShow: 6,
    slidesToScroll: 3,
  };
  const { news } = useSelector((store: State) => store.newsManager);
  const { mobiles } = useSelector((store: State) => store.productsManager);
  const dispatch = useDispatch();
  useEffect(() => {
    if (news.length === 0) {
      getNews(dispatch, 15);
      getMobile(dispatch);
    }
  }, []);
  console.log(mobiles);

  return (
    <>
      <Head>
        <title>GadgetRambo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        {/* left side bar of homepage starts  */}
        <div className={styles.left_sideBar}>
          <Text
            color={"var(--color-primary)"}
            fontSize={"18px"}
            fontWeight={"400"}
          >
            TRENDING
          </Text>
          {news.map((el: any, index: number) => {
            if (index >= 10) {
              return;
            }
            return (
              <NewsCard
                key={el.id}
                title={el.title}
                titleSize={"13px"}
                banner={el.banner}
                imgHeight={"100px"}
                titleMaxHeight={"3.9rem"}
              />
            );
          })}
        </div>
        {/* middle contents starts  */}
        <div className={styles.mainContainer}>
          {/* indepth section starts here  */}
          <div className={styles.inDepthBox}>
            <p>IN-DEPTH</p>
            <div style={{ display: "flex", gap: "2rem" }}>
              {news.map((el: any, index: number) => {
                if (index >= 4) {
                  return;
                }
                return (
                  <NewsCard
                    cardWidth="25%"
                    key={el.id}
                    title={el.title}
                    titleSize={"15px"}
                    banner={el.banner}
                    imgHeight={"120px"}
                    titleMaxHeight={"4.2rem"}
                  />
                );
              })}
            </div>
          </div>
          {/* product finder section start here  */}
          <div className={styles.productFinderBox}>
            <p>PRODUCT FINDER</p>
            <div className={styles.productFinderContent}>
              {/* product slider section */}
              <Slider {...settings}>
                {productFinderArr.map((item, id) => (
                  <Box
                    key={id}
                    borderRight={"1px solid #eae8e8"}
                    cursor={"pointer"}
                    background={"var(--color-bg-light)"}
                  >
                    <item.icon
                      style={{ fontSize: "30px", margin: "1rem auto" }}
                    />
                    <Text
                      color={"var(--color-light)"}
                      fontSize={"12px"}
                      whiteSpace={"nowrap"}
                      textAlign={"center"}
                    >
                      {item.name}
                    </Text>
                  </Box>
                ))}
              </Slider>
              {/* popular phones section  */}
              <p>Popular Phones</p>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-evenly",
                  backgroundColor: "white",
                  margin: ".4rem",
                  borderRadius: ".5rem",
                }}
              >
                {mobiles.map((mobile: any, id: number) => {
                  if (id >= 6) {
                    return;
                  }
                  return (
                    <NewsCard
                      key={mobile.id}
                      title={mobile.modal}
                      banner={mobile.imgsrc}
                      titleSize={"15px"}
                      cardWidth={"16%"}
                      imgHeight={"100px"}
                      titleAlign={true}
                    />
                  );
                })}
              </div>
              {/* latest phones section  */}
              <p>Latest Phones</p>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-evenly",
                  backgroundColor: "white",
                  margin: ".4rem",
                  borderRadius: ".5rem",
                }}
              >
                {mobiles.map((mobile: any, id: number) => {
                  if (id >= 6) {
                    return;
                  }
                  return (
                    <NewsCard
                      key={mobile.id}
                      title={mobile.modal}
                      banner={mobile.imgsrc}
                      titleSize={"15px"}
                      cardWidth={"16%"}
                      imgHeight={"100px"}
                      titleAlign={true}
                    />
                  );
                })}
              </div>
              {/* upcoming phones section  */}
              <p>Upcoming Phones</p>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-evenly",
                  backgroundColor: "white",
                  margin: ".4rem",
                  borderRadius: ".5rem",
                }}
              >
                {mobiles.map((mobile: any, id: number) => {
                  if (id >= 6) {
                    return;
                  }
                  return (
                    <NewsCard
                      key={mobile.id}
                      title={mobile.modal}
                      banner={mobile.imgsrc}
                      titleSize={"15px"}
                      cardWidth={"16%"}
                      imgHeight={"100px"}
                      titleAlign={true}
                    />
                  );
                })}
              </div>
              {/* popular comparisons carousel  */}
              {/* <Slider {...ComparisonCarouselSettings}>
                {mobiles.map((mobile: any, id) => {
                  if (id >= 20) {
                    return;
                  }
                  return (
                    <NewsCard
                      key={mobile.id}
                      title={mobile.modal}
                      banner={mobile.imgsrc}
                      titleSize={"15px"}
                      cardWidth={"16%"}
                      imgHeight={"100px"}
                      titleAlign={true}
                    />
                  );
                })}
              </Slider> */}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
